/**
 * Client configuration for this deployment.
 *
 * NOTE: no skill reads this module. At runtime the skills read the client's facts
 * from Airtable (Business Profile, Region Naming, Region Travel, Email Templates),
 * written by `client-onboarding` and `voice-intake`. Its only consumer today is the
 * maintainer script `scripts/setup-airtable.mjs`, which needs `segments` to decide
 * whether to provision the Corporate Research table. `client-data.json` itself IS
 * used by the skills — it is synced into `email-generation` as the example fallback.
 *
 * Client-interview answers (facts) live in ./client-data.json — regenerated by
 * the client-onboarding intake skill, kept out of this hand-maintained file.
 * This module loads and VALIDATES that data, merges it with the operational
 * pipeline config below (set by the operator, not the client), and exports the
 * same shape consumers have always used.
 *
 * To deploy for a different client: re-run the onboarding intake (regenerates
 * client-data.json) — no logic changes here.
 */

import clientData from "./client-data.json" with { type: "json" };

// Required intake fields. The loader fails loudly (naming the field) when the
// data file is incomplete, so a bad intake surfaces here, not as a cryptic
// downstream error.
const REQUIRED_FIELDS = [
  "businessName",
  "businessUrl",
  "location",
  "signingName",
  "signature",
  "propertyContext",
  "segments",
];

export function validateClientData(data) {
  if (!data || typeof data !== "object") {
    throw new Error("client-data.json: expected a JSON object");
  }
  for (const field of REQUIRED_FIELDS) {
    const value = data[field];
    const empty =
      value === undefined ||
      value === null ||
      (typeof value === "string" && value.trim() === "") ||
      (Array.isArray(value) && value.length === 0);
    if (empty) {
      throw new Error(`client-data.json: required field "${field}" is missing or empty`);
    }
  }
  if (!Array.isArray(data.segments)) {
    throw new Error(`client-data.json: "segments" must be an array`);
  }
  const hasRegions = Array.isArray(data.targetRegions) && data.targetRegions.length > 0;
  const hasGeographies = Array.isArray(data.targetGeographies) && data.targetGeographies.length > 0;
  if (!hasRegions && !hasGeographies) {
    throw new Error('client-data.json: must provide "targetRegions" (or legacy "targetGeographies")');
  }
  if (hasRegions) {
    for (const r of data.targetRegions) {
      if (!r || typeof r.metro !== "string" || r.metro.trim() === "") {
        throw new Error('client-data.json: each targetRegions entry needs a non-empty "metro"');
      }
    }
  }
  return data;
}

// targetRegions (objects, metro required) is the source of truth. targetGeographies
// (a flat metro list) is DERIVED for Stage 01 / legacy consumers. Legacy data that
// has only targetGeographies is accepted by synthesizing minimal region objects.
export function normalizeRegions(data) {
  const hasRegions = Array.isArray(data.targetRegions) && data.targetRegions.length > 0;
  const targetRegions = hasRegions
    ? data.targetRegions
    : (data.targetGeographies || []).map((metro) => ({ metro }));
  const targetGeographies = targetRegions.map((r) => r.metro);
  return { targetRegions, targetGeographies };
}

const facts = validateClientData(clientData);
const regions = normalizeRegions(facts);

const client = {
  ...facts,
  ...regions,

  // ---- Operational config (NOT client intake — set by the operator) ----

  // OPTIONAL pre-seed for the geocoder cache — saves one Nominatim call per
  // known city. Absent/empty is non-fatal: those cities geocode on first use.
  // Left empty in the template; an operator may pre-seed their own target cities.
  geoSeed: [],

  // Stage 01 pagination. Each page is 20 results (~1 credit). Pages 4+ surface
  // more vendors/venues than planners, so cap at 3.
  discoveryMaxPages: 3,
  discoveryMaxResults: 60, // informational ceiling = discoveryMaxPages × 20

  // Stage 01 search terms per segment. A string runs one query per city; an
  // array runs each term and merges + dedupes results.
  discoverySearchTerms: {
    Wedding: "wedding planner",
    Corporate: [
      "corporate event planner",
      "corporate retreat planner",
      "destination management company",
    ],
  },

  // Delivery mode (operator-owned). "packet" = copy-paste send packet (Approach A);
  // "imap-draft" = drafts into the operator's mailbox (Approach B, future);
  // "both" = packet + drafts.
  delivery: {
    mode: "packet",
  },

  // Airtable base — set in .env, referenced here for documentation
  // airtableBaseId: process.env.AIRTABLE_BASE_ID
};

export default client;
